name: Pre-commit
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
jobs:
  pre_commit:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Run pre-commit
        uses: njzjz/pre-commit-action@master
      - name: Check citation key compatibility
        run: uv run --with bibtexparser==2.0.0b7 python .scripts/test_check_bibtex.py
